### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by bill-rich** [ucloud/terraform-provider-ucloud-old#19]
Hello! 

My name is Bill, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit  b60f089e343d0cde61199a799b5e2c97dfd85ee8.

## General
- [x] Does `resourceUCloudDiskCreate` need to call `resourceUCloudDiskUpdate`? It doesn’t look like `Update` sets anything that `Create` doesn’t. It looks like this is a common pattern in the resource create functions. Is there post create updates that need to happen?
- [x] Add import tests for resources which support importing. These can be included as part of the basic test if you would like.
- [x] You might want to use a constant for some states like “pending” as they are regularly used.
- [x] Errors should be checked when setting non-scalars like `ip_set` in `resource_ucloud_eip` to ensure the value is properly formatted and set.
- [x] If the order of `ip_set` (and other TypeLists) could change, using `TypeSet` would be better than `TypeList`. The order of items matters in `TypeList`, but not in `TypeSet`.
- [x] What happens if the `instance` `tag` argument is "" rather than "Default"?
- [x] Translate arguments and attributes such as `instance`  `auto_renew` into boolean values rather than using a string value which needs to be interpreted.
- [x] In README.md, "Refer" looks like it should be "Reference"
- [x] CHANGELOG.md needs to be added
- [x] Check that data sources have arguments and attributes assigned correctly. It looks like the data source schemas may just be a copy of the resources, but some things like `tags` may not be an item that should be used for looking up `instance`s. 
- [x] `ForceNew` is not needed for data sources.

## Documentation
- [x] List defaults in "Default: Value" format.
- [x] If an int is expected, list the unit separately. eg "Size of disk in GB. 1-8000 for a cloud disk, or 1-4000 for an SSD cloud disk."
- [x] Use backticks for values in docs. eg `DataDisk` instead of "DataDisk".
- [x] General grammar proof reading in docs (also some in code comments, but less important there). There are some sentence syntax, capitalization, and punctuation issues.
- [x] Check character use. `instance` resource docs contain "，" in place of a space.

**Comment by tangjunjie119** [comment]
Hi Bill@bill-rich , 

Thanks for reviewing, please find our replies accordingly below, 

**General**
1. The `update` pattern is only required when creating specific resource as to set schema with value, which also could avoid the code redundancy. We will remove the `update` pattern to make it clearer if no such value needs to be set after creation.
2. We will try to add import tests to parts of the resources along with the next release due to limited time, the rest will be added as soon as we are ready.
3. Yes, we will check and set the state as constant where necessary.
4. The error checking logic will be added.
5. We will use `TypeSet` for arguments as the order of items could change, and use `TypeList`for attributes as the order of item is unlikely to change.
6. The validation on `instance tag` argument will be added to ensure no "".
7. We will check and translate the arguments and attributes into boolean value where necessary as required.
8. Will be corrected.
9. Will be added.
10. The data source which looks like a copy of resource as you mentioned is only for query purpose, we will check and remove for better understanding, such argument like `tags` will be removed as well.
11. Will be removed.

**Documentation**
12. Will be updated as required.
13. Will be updated as required.
14. Will be updated as required.
15. Will be corrected as required.
16. Will be updated as required.

Our target date for next release is this Friday (China time before US working hour) to include the above changes if no more issue, it will be **GREAT** and much appreciated if you could complete your second review by this Friday (US time), so that we both could prepare for the official release by next week prior to winter shut down (which is 22nd Dec and roughly 1.5 weeks to go I guess?).

Please be advised that the refinement of code style will also be included in the following release, you may refer to the Git repository for more details.

Jason

**Comment by bill-rich** [comment]
Hi @tangjunjie119! That sounds great! I will give everything another look first thing on Friday, so that you can have the review ready to start the week if another round of review is needed.

**Comment by tangjunjie119** [comment]
Hi Bill @bill-rich,

We've managed to make the release on master branch by today, our engineer will provide the commit ID later. Please have another look and let us konw if we can finalize the review and proceed with the steps. Thank you.

Jason

**Comment by shawnmssu** [comment]
We've make the release on master branch, https://github.com/ucloud/terraform-provider-ucloud/commit/514e2926c029137375c7d4565d528453e0967c74 ([v0.2.0](https://github.com/ucloud/terraform-provider-ucloud/releases/tag/v0.2.0)).

**Comment by bill-rich** [comment]
It is looking great! I've got a couple followup questions and suggestions, but I think we're almost there. 

1) On `What happens if the instance tag argument is "" rather than "Default"?`, the validation looks good, but would a default work in that field? As it is now, it is listed as optional, but I believe if it is not filled in, the plan will fail to pass validation.
2) Please fill in some basic info in CHANGELOG.md. It can just be basic info about which data sources and resources are included in the initial release. See https://github.com/terraform-providers/terraform-provider-oraclepaas/commit/d615a8b1fa9010df6e0605834e502fd25369df41#diff-4ac32a78649ca5bdd8e0ba38b7006a1e for an example.
3) When using the backticks in the documentation, the quotes are not necessary. For example, instead of `"example_string"`, it is ok to just use `example_string`.

**Comment by tangjunjie119** [comment]
Hi Bill @bill-rich ,

Please find our replies below accordingly, 

1. The current logic is: if it is not filled in or filled in with ``, a default tag will be assigned. The validation will pass and no failure will be occurred under such circumstances by now.
2. The basic info has been added to CHANGELOG.md as required.
3. The quotes have been removed when using the backticks in the documentation as required.

We've pushed a new release to the master branch at git release [v0.2.1](https://github.com/ucloud/terraform-provider-ucloud/releases/tag/v0.2.1) , please take a look at your earliest convenience, hopefully all the issues should be addressed by now. Thanks a lot.

Jason

**Comment by bill-rich** [comment]
Thanks @tangjunjie119! Looks like you have everything covered. I appreciate you taking the time to address these issues.
